name: 'Publish Immutable Action Version'

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      packages: write

    steps:
      - name: Check release name
        id: check
        env:
          RELEASE_NAME: ${{ github.event.release.name }}
        run: |
          echo "Release name: $RELEASE_NAME"
          if [[ "$RELEASE_NAME" == v* ]]; then
            echo "This is a CodeQL Action release. Create an Immutable Action"
            echo "is-action-release=true" >> $GITHUB_OUTPUT
          else
            echo "This is a CodeQL Bundle release. Do not create an Immutable Action"
            echo "is-action-release=false" >> $GITHUB_OUTPUT
          fi
      - name: Checking out
        if: steps.check.outputs.is-action-release == 'true'
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - name: Publish
        if: steps.check.outputs.is-action-release == 'true'
        id: publish
        uses: actions/publish-immutable-action@4bc8754ffc40f27910afb20287dbbbb675a4e978 # v0.0.4
